spring:
  profiles:
    active: dev # 表示开发环境
  application:
    name: alibaba-seata-storage
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.43:33061/seata_example_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: cDe3@wsx
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shunyi.autoparts.entities
#  在 Nacos Spring Cloud 中，dataId 的完整格式如下：

#  ${prefix}-${spring.profiles.active}.${file-extension}
#  最终文件名： alibaba-config-server-dev.yml