spring:
  application:
    name: payment-consul
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.3.25:33061/autoparts?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: cDe3@wsx
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shunyi.autoparts.entities