spring:
  application:
    name: payment-alibaba-app
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12385361?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: sql12385361
      password: qCQVGbAPjC
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shunyi.autoparts.entities