server:
  port: 10005
spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://localhost/config-repo
          clone-on-start: true

  security:
    user:
      name: 526637060@qq.com
      password: 123
